apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.23.4 # change according to kubeadm supported version
clusterName: kubernetes
imageRepository: k8s.gcr.io
controlPlaneEndpoint: haproxy:6443
certificatesDir: /etc/kubernetes/pki
etcd:
  external:
      endpoints:
      - https://172.20.10.13:2379      
      - https://172.20.10.2:2379      
      - https://172.20.10.4:2379 
      caFile: /etc/kubernetes/pki/etcd/ca.crt
      certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
      keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key 
dns:
  type: CoreDNS
  imageRepository: "k8s.gcr.io/coredns/coredns"
  imageTag: "v1.8.6"  
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.233.0.0/18
  podSubnet: 10.233.64.0/18
apiServer:
  extraArgs:
    default-not-ready-toleration-seconds: "300"
    default-unreachable-toleration-seconds: "300"
    anonymous-auth: "false"
    authorization-mode: ['Node', 'RBAC']  
    bind-address: 0.0.0.0
    kube_apiserver_count: 1
    endpoint-reconciler-type: lease
    service-node-port-range: "30000-32767"
    service-cluster-ip-range: 10.233.0.0/18
    kubelet-preferred-address-types: 'InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP'
    profiling: "false"
    request-timeout: "1m0s"
    enable-aggregator-routing: "false"
    storage-backend: etcd3
    allow-privileged: "true"
    event-ttl: "1h0m0s"
  certSANs:
  - "127.0.0.1"
  - "localhost"
  - "kubernetes"
  - "kubernetes.default"
  - "kubernetes.default.svc"
  - "kubernetes.default.svc.cluster.local"
  - "haproxy"
  - "172.20.10.19"
  - "master1"
  - "172.20.10.14"
  timeoutForControlPlane: 5m0s
controllerManager:
  extraArgs: 
    node-monitor-grace-period: 40s
    node-monitor-period: 5s
    cluster-cidr: 10.233.64.0/18
    service-cluster-ip-range: 10.233.0.0/18 
    node-cidr-mask-size: "24"
    profiling: "false"
    terminated-pod-gc-threshold: "12500"
    bind-address: 0.0.0.0
    leader-elect-lease-duration: 15s
    leader-elect-renew-deadline: 10s
    configure-cloud-routes: "false"
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: '0.0.0.0'
clientConnection:
  acceptContentTypes: ''
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: ''
  qps: 5
clusterCIDR: 10.233.64.0/18
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
enableProfiling: false 
healthzBindAddress: 0.0.0.0:10256
iptables:
  masqueradeAll: false 
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  excludeCIDRs: []
  minSyncPeriod: 0s
  scheduler: rr
  syncPeriod: 30s
  strictARP: false
  tcpTimeout: 0s
  tcpFinTimeout: 0s
  udpTimeout: 0s
metricsBindAddress: 127.0.0.1:10249
mode: ipvs 
nodePortAddresses: []
oomScoreAdj: -999
portRange: ''
udpIdleTimeout: 250ms
